apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: etax-web-service
  labels:
    app: etax
spec:
  type: NodePort
  ports:
  - port: 9000
    name: etax-web-service-port
    targetPort: 9000
    nodePort: 30000
  selector:
    component: etax-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etax-web-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: etax
        component: etax-web
        tier: frontend
    spec:
      containers:
      - name: etax-web-container
        image: dhanuwat/etax-web:v1.0.5
        ports:
        - containerPort: 9000
      imagePullSecrets:
      - name: regcred