apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: etax-report-service
  labels:
    app: etax
spec:
  type: NodePort
  ports:
  - port: 30543
    name: etax-report-service-port
    targetPort: 30543
    nodePort: 30543
  selector:
    component: etax-report
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etax-report-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: etax
        component: etax-report
        tier: backend
    spec:
      containers:
      - name: etax-report-container
        image: dhanuwat/etax-report:v1.0.6
        env:
        - name: Link__API
          value: "http://localhost:30542"
        - name: Link__IdentityAPI
          value: "http://localhost:30540"
        - name: LinkDocker__API
          value: "http://localhost:30542"
        - name: LinkDocker__IdentityAPI
          value: "http://localhost:30540"
        ports:
        - containerPort: 30543
      imagePullSecrets:
      - name: regcred