apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: etax-identity-service
  labels:
    app: etax
spec:
  type: NodePort
  ports:
  - port: 30540
    name: etax-identity-service-port
    targetPort: 30540
    nodePort: 30540
  selector:
    component: etax-identity
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etax-identity-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: etax
        component: etax-identity
        tier: backend
    spec:
      containers:
      - name: etax-identity-container
        image: dhanuwat/etax-identity:v1.0.1
        ports:
        - containerPort: 30540
      imagePullSecrets:
      - name: regcred