apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: etax-mysql-web-service
  labels:
    app: etax-mysql
spec:
  type: NodePort
  ports:
  - port: 30600
    name: etax-mysql-web-service-port
    targetPort: 30600
    nodePort: 30600
  selector:
    component: etax-mysql-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etax-mysql-web-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: etax-mysql
        component: etax-mysql-web
        tier: frontend-mysql
    spec:
      containers:
      - name: etax-mysql-web-container
        image: dhanuwat/etax-web:mysql-v1.0.0
        ports:
        - containerPort: 30600
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: etax-mysql-api-service
  labels:
    app: etax-mysql
spec:
  type: NodePort
  ports:
  - port: 30642
    name: etax-mysql-api-service-port
    targetPort: 30642
    nodePort: 30642
  selector:
    component: etax-mysql-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etax-mysql-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: etax-mysql
        component: etax-mysql-api
        tier: backend
    spec:
      containers:
      - name: etax-mysql-api-container
        image: dhanuwat/etax-api:mysql-v1.0.0
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=203.154.58.85;Database=etax_stage_smoothe;User ID=root;Password=P@ssw0rd;"
        - name: Link__IdentityAPI
          value: "http://etax-mysql-identity-service:30640"
        - name: LinkDocker__IdentityAPI
          value: "http://etax-mysql-identity-service:30640"
        - name: StartPort
          value: "30642"
        ports:
        - containerPort: 30642
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: 30642
          initialDelaySeconds: 15
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: etax-mysql-identity-service
  labels:
    app: etax-mysql
spec:
  type: NodePort
  ports:
  - port: 30640
    name: etax-mysql-identity-service-port
    targetPort: 30640
    nodePort: 30640
  selector:
    component: etax-mysql-identity
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etax-mysql-identity-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: etax-mysql
        component: etax-mysql-identity
        tier: backend
    spec:
      containers:
      - name: etax-mysql-identity-container
        image: dhanuwat/etax-identity:mysql-v1.0.0
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=203.154.58.85; Database=etaxidentity_stage_smoothe; User ID=root ;Password=P@ssw0rd;"
        - name: ConnectionStrings__EtaxConnection
          value: "Server=203.154.58.85; Database=etax_stage_smoothe; User ID=root ;Password=P@ssw0rd;"
        - name: Link__API
          value: "http://etax-mysql-api-service:30642"
        - name: Link__IdentityAPI
          value: "http://etax-mysql-identity-service:30640"
        - name: Link__Client
          value: "http://203.154.59.95:30600"
        - name: LinkDocker__API
          value: "http://etax-mysql-api-service:30640"
        - name: LinkDocker__IdentityAPI
          value: "http://etax-mysql-identity-service:30640"
        - name: LinkDocker__Client
          value: "http://203.154.59.95:30600"
        - name: StartPort
          value: "30640"
        ports:
        - containerPort: 30640
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: 30640
          initialDelaySeconds: 15
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: etax-mysql-report-service
  labels:
    app: etax-mysql
spec:
  type: NodePort
  ports:
  - port: 30643
    name: etax-mysql-report-service-port
    targetPort: 30643
    nodePort: 30643
  selector:
    component: etax-mysql-report
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etax-mysql-report-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: etax-mysql
        component: etax-mysql-report
        tier: backend
    spec:
      containers:
      - name: etax-mysql-report-container
        image: dhanuwat/etax-report:mysql-v1.0.0
        env:
        - name: Link__API
          value: "http://etax-mysql-api-service:30642"
        - name: Link__IdentityAPI
          value: "http://etax-mysql-identity-service:30640"
        - name: LinkDocker__API
          value: "http://etax-mysql-api-service:30642"
        - name: LinkDocker__IdentityAPI
          value: "http://etax-mysql-identity-service:30640"
        - name: StartPort
          value: "30643"
        ports:
        - containerPort: 30643
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: 30643
          initialDelaySeconds: 15
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: regcred
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: etax-mysql-api-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: etax-mysql-api-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: etax-mysql-identity-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: etax-mysql-identity-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: etax-mysql-report-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: etax-mysql-report-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50