apiVersion: v1
kind: Pod
metadata:
  name: etax-web-pod
  labels:
    app: etax-web
spec:
  containers:
  - name: etax-web-container
    image: dhanuwat/etax.web:stage
    ports:
    - name: etax-web-port
      containerPort: 4200
  imagePullSecrets:
    - name: regcred